# **Arithmetic Operation**

## **Arithmetic Operators**
| Operator | Meaning               | Equivalent NumPy Function |
| -------- | --------------------- | ------------------------- |
| `+`      | Addition              | `np.add(a, b)`            |
| `-`      | Subtraction           | `np.subtract(a, b)`       |
| `*`      | Element-wise multiply | `np.multiply(a, b)`       |
| `/`      | True division         | `np.divide(a, b)`         |
| `//`     | Floor division        | `np.floor_divide(a, b)`   |
| `%`      | Modulus               | `np.mod(a, b)`            |
| `**`     | Power                 | `np.power(a, b)`          |


## **Arithmetic Operators on 1D Array**

In [2]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])


### Addition

In [3]:
a+3
np.add(a,3)
# Output :array([4, 5, 6, 7, 8])
a+b
np.add(a,b)
# Output : array([6, 6, 6, 6, 6])

array([6, 6, 6, 6, 6])

### Subtraction 

In [4]:
a-2
np.subtract(a,2)
# Ouptput : array([-1,  0,  1,  2,  3])
a-b
np.subtract(a,b)
# Output : array([-4, -2,  0,  2,  4])

array([-4, -2,  0,  2,  4])

### Element-wise Multiply

In [5]:
a*2
np.multiply(a,2)
# Output : array([ 2,  4,  6,  8, 10])
a*b
np.multiply(a,b)
# Output : array([5, 8, 9, 8, 5])

array([5, 8, 9, 8, 5])

### Division

In [6]:
a/2
np.divide(a,2)
# Output : array([0.5, 1. , 1.5, 2. , 2.5])
a/b
np.divide(a,b)
# Output : array([0.2, 0.5, 1. , 2. , 5. ])

array([0.2, 0.5, 1. , 2. , 5. ])

### Floor Division

In [7]:

a//2
np.floor_divide(a,2)
# Output : array([0, 1, 1, 2, 2])
a//b
np.floor_divide(a,b)
# Output : array([0, 0, 1, 2, 5])

array([0, 0, 1, 2, 5])

### Modulus

In [8]:
a%2
np.mod(a,2)
# Output : array([1, 0, 1, 0, 1])
a%b
np.mod(a,b)
# Output : array([1, 2, 0, 0, 0])

array([1, 2, 0, 0, 0])

### Power

In [9]:
a**2
np.power(a,2)
# Output : array([ 1,  4,  9, 16, 25])
a**b
np.power(a,b)
# Output : array([ 1, 16, 27, 16,  5])

array([ 1, 16, 27, 16,  5])

## **Arithmetic Operators on 2D Array**

In [10]:
a=np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([[4,3,2,1],[4,3,2,1]])

### Addition

In [11]:
a+2
np.add(a,2)
# Output :array([[3, 4, 5, 6],[3, 4, 5, 6]])
a+b
np.add(a,b)
# Output : array([[5, 5, 5, 5],[5, 5, 5, 5]])

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

### Subtraction

In [12]:
a-2
np.subtract(a,2)
# Ouptput : array([[-1,  0,  1,  2],[-1,  0,  1,  2]])
a-b
np.subtract(a,b)
# Output : array([[-3, -1,  1,  3],[-3, -1,  1,  3]])

array([[-3, -1,  1,  3],
       [-3, -1,  1,  3]])

### Element-Wise Multiply

In [13]:
a*2
np.multiply(a,2)
# Output : array([[2, 4, 6, 8],[2, 4, 6, 8]])
a*b
np.multiply(a,b)
# Output : array([[4, 6, 6, 4],[4, 6, 6, 4]])

array([[4, 6, 6, 4],
       [4, 6, 6, 4]])

### Division

In [14]:
a/2
np.divide(a,2)
# Output : array([[0.5, 1. , 1.5, 2. ],[0.5, 1. , 1.5, 2. ]])
a/b
np.divide(a,b)
# Output : array([[0.25 , 0.66666667, 1.5 , 4. ],[0.25 , 0.66666667, 1.5 , 4]])

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [0.25      , 0.66666667, 1.5       , 4.        ]])

### Floor Division

In [15]:
a//2
np.floor_divide(a,2)
# Output : array([[0, 1, 1, 2],[0, 1, 1, 2]])
a//b
np.floor_divide(a,b)
# Output : array([[0, 0, 1, 4],[0, 0, 1, 4]])

array([[0, 0, 1, 4],
       [0, 0, 1, 4]])

### Modulus

In [16]:
a%2
np.mod(a,2)
# Output : array([[1, 0, 1, 0],[1, 0, 1, 0]])
a%b
np.mod(a,b)
# Output : array([[1, 2, 1, 0],[1, 2, 1, 0]])

array([[1, 2, 1, 0],
       [1, 2, 1, 0]])

### Power

In [17]:
a**2
np.power(a,2)
# Output : array([[ 1,  4,  9, 16],[ 1,  4,  9, 16]])
a**b
np.power(a,b)
# Output : array([[1, 8, 9, 4],[1, 8, 9, 4]])

array([[1, 8, 9, 4],
       [1, 8, 9, 4]])

---
#### *Some Traps*

In [18]:
a=np.array([1,3,5])
b=np.array([2,4,6,8])
c=np.array([2.2,3.3,4.4])
a+c

array([3.2, 6.3, 9.4])

In [19]:
# a+b 
# c+b
# Error Cause of Different Shape

In [20]:
a+c # Int and Float operations are Possible

array([3.2, 6.3, 9.4])

---
# **Practice Problems**

##### 1️⃣

Create a **6×6 matrix** where:

* Each row increases by **1**
* Each column increases by **10**

📌 Output pattern:

```
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 ...
]
```

In [21]:
np.arange(0,6)+np.arange(0,60,10).reshape(6,1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

##### 2️⃣

Given:

```python
A = np.arange(1, 7)
B = np.arange(6).reshape(6,1)
```

Create a matrix where:

```
result[i][j] = A[j] * B[i]
```


In [22]:
A=np.arange(1,7)
B=np.arange(6).reshape(6,1)
A*B
B*A

array([[ 0,  0,  0,  0,  0,  0],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30]])

##### 3️⃣

Create a **5×5** array where:

* Diagonal = 1
* Above diagonal = 2
* Below diagonal = 3

📌 No conditionals (`if`) allowed.


In [66]:
diagonal=np.eye(5,5,k=0)
upper=np.ones((5,5))
upper=np.triu(upper,k=1)*2
lower=np.ones((5,5))
lower=np.tril(lower,k=-1)*3
result=diagonal+upper+lower
result.astype(int)

array([[1, 2, 2, 2, 2],
       [3, 1, 2, 2, 2],
       [3, 3, 1, 2, 2],
       [3, 3, 3, 1, 2],
       [3, 3, 3, 3, 1]])

In [65]:
n = 5
arr = np.full((n,n), 2)
arr[np.tril_indices(n,-1)] = 3
arr[np.diag_indices(n)] = 1
arr


array([[1, 2, 2, 2, 2],
       [3, 1, 2, 2, 2],
       [3, 3, 1, 2, 2],
       [3, 3, 3, 1, 2],
       [3, 3, 3, 3, 1]])

##### 4️⃣

Given a 1D array:

```python
arr = np.array([2, 4, 6, 8])
```

Create a matrix where:

```
M[i][j] = arr[i] + arr[j]
```

In [63]:
arr=np.array([2,4,6,8])
arr+arr.reshape(-1,1)

array([[ 4,  6,  8, 10],
       [ 6,  8, 10, 12],
       [ 8, 10, 12, 14],
       [10, 12, 14, 16]])

##### 5️⃣

Given:

```python
x = np.arange(1, 11)
```

Create:

```
y = (x² + 3x + 5) / (x + 1)
```

Return **only integers** (no decimals).

In [71]:
x=np.arange(1,11)
y=((x**2 + 3*x + 5)//(x+1))
y

array([ 4,  5,  5,  6,  7,  8,  9, 10, 11, 12])

##### 6️⃣

Create a 1D array of size **10** where:

* Even indices → square of index
* Odd indices → cube of index

❌ No loops
❌ No `np.where`

In [40]:
arr=np.arange(0,10)
arr[0::2]=arr[0::2]**2
arr[1::2]=arr[1::2]**3
arr

array([  0,   1,   4,  27,  16, 125,  36, 343,  64, 729])

##### 7️⃣

Normalize this array **between 0 and 1**:

```python
arr = np.array([15, 20, 35, 50, 80])
```


In [27]:
arr=np.array([15,20,35,50,80])
norm_arr=(arr-arr.min())/(arr.max()-arr.min())
norm_arr

array([0.        , 0.07692308, 0.30769231, 0.53846154, 1.        ])


##### 8️⃣

Compute the **row-wise Euclidean norm** of:

```python
A = np.array([[3,4], [5,12], [8,15]])
```

📌 Output shape → `(3,)`

In [ ]:
A=np.array([[3,4],[5,12],[8,15]])
# A=A**2
# A=A.sum(axis=1)
# np.sqrt(A)

# OR

np.sqrt(np.sum(A**2, axis=1))

# OR

np.linalg.norm(A,axis=1)

array([ 5., 13., 17.])

##### 9️⃣

Given:

```python
arr = np.array([1, 2, 3, 4, 5])
```

Compute:

```
[(1² + 2²), (2² + 3²), (3² + 4²), (4² + 5²)]
```

📌 No loops


In [ ]:
arr=np.array([1,2,3,4,5])
arr=arr**2
arr[:-1]+arr[1:]

np.add(arr[:-1],arr[1:])

array([ 5, 13, 25, 41])


##### 🔟

Given:

```python
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
```

Replace:

* Even numbers → square
* Odd numbers → cube

📌 Do it **in one expression**


In [35]:
A=np.arange(0,10)
np.where(A%2==0,arr**2,arr**3)

#OR

is_even=(A%2==0)
is_odd=(A%2==1)

result=(A**2 * is_even)+(A**3 * is_odd)
result

array([  0,   1,   4,  27,  16, 125,  36, 343,  64, 729])


##### 1️⃣1️⃣

Given:

```python
x = np.arange(1, 6)
```

Create a **multiplication table**:

```
[[1, 2, 3, 4, 5],
 [2, 4, 6, 8,10],
 ...
]
```

📌 No loops


In [ ]:
x=np.arange(1,6)
x*x.reshape((5,1))

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

##### 1️⃣2️⃣

Create a matrix where:

```
M[i][j] = |i - j|
```

Size: **6×6**


In [54]:
i=np.arange(6)
j=np.arange(6).reshape(6,1)
np.abs(i-j)

array([[0, 1, 2, 3, 4, 5],
       [1, 0, 1, 2, 3, 4],
       [2, 1, 0, 1, 2, 3],
       [3, 2, 1, 0, 1, 2],
       [4, 3, 2, 1, 0, 1],
       [5, 4, 3, 2, 1, 0]])


##### 1️⃣3️⃣ (INTERVIEW LEVEL)

Given:

```python
arr = np.arange(1, 11)
```

Compute:

```
[log(x) if x even else sqrt(x)]
```

❌ No loops
❌ No Python `if`
📌 NumPy only

In [55]:
arr=np.arange(1,11)
np.where(arr%2==0,np.log(arr),np.sqrt(arr))

array([1.        , 0.69314718, 1.73205081, 1.38629436, 2.23606798,
       1.79175947, 2.64575131, 2.07944154, 3.        , 2.30258509])

##### 1️⃣4️⃣

Create a **5×5** matrix where:

* Each element = `(row_index + 1)^(column_index + 1)`

📌 Broadcasting only
📌 No loop

In [73]:
rows=np.arange(1,6)
cols=np.arange(1,6).reshape(-1,1)
result=rows**cols
result

array([[   1,    2,    3,    4,    5],
       [   1,    4,    9,   16,   25],
       [   1,    8,   27,   64,  125],
       [   1,   16,   81,  256,  625],
       [   1,   32,  243, 1024, 3125]])