# **Arithmetic Operation**

## **Arithmetic Operators**
| Operator | Meaning               | Equivalent NumPy Function |
| -------- | --------------------- | ------------------------- |
| `+`      | Addition              | `np.add(a, b)`            |
| `-`      | Subtraction           | `np.subtract(a, b)`       |
| `*`      | Element-wise multiply | `np.multiply(a, b)`       |
| `/`      | True division         | `np.divide(a, b)`         |
| `//`     | Floor division        | `np.floor_divide(a, b)`   |
| `%`      | Modulus               | `np.mod(a, b)`            |
| `**`     | Power                 | `np.power(a, b)`          |


## **Arithmetic Operators on 1D Array**

In [1]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])


### Addition

In [2]:
a+3
np.add(a,3)
# Output :array([4, 5, 6, 7, 8])
a+b
np.add(a,b)
# Output : array([6, 6, 6, 6, 6])

array([6, 6, 6, 6, 6])

### Subtraction 

In [3]:
a-2
np.subtract(a,2)
# Ouptput : array([-1,  0,  1,  2,  3])
a-b
np.subtract(a,b)
# Output : array([-4, -2,  0,  2,  4])

array([-4, -2,  0,  2,  4])

### Element-wise Multiply

In [4]:
a*2
np.multiply(a,2)
# Output : array([ 2,  4,  6,  8, 10])
a*b
np.multiply(a,b)
# Output : array([5, 8, 9, 8, 5])

array([5, 8, 9, 8, 5])

### Division

In [5]:
a/2
np.divide(a,2)
# Output : array([0.5, 1. , 1.5, 2. , 2.5])
a/b
np.divide(a,b)
# Output : array([0.2, 0.5, 1. , 2. , 5. ])

array([0.2, 0.5, 1. , 2. , 5. ])

### Floor Division

In [6]:

a//2
np.floor_divide(a,2)
# Output : array([0, 1, 1, 2, 2])
a//b
np.floor_divide(a,b)
# Output : array([0, 0, 1, 2, 5])

array([0, 0, 1, 2, 5])

### Modulus

In [7]:
a%2
np.mod(a,2)
# Output : array([1, 0, 1, 0, 1])
a%b
np.mod(a,b)
# Output : array([1, 2, 0, 0, 0])

array([1, 2, 0, 0, 0])

### Power

In [8]:
a**2
np.power(a,2)
# Output : array([ 1,  4,  9, 16, 25])
a**b
np.power(a,b)
# Output : array([ 1, 16, 27, 16,  5])

array([ 1, 16, 27, 16,  5])

## **Arithmetic Operators on 2D Array**

In [9]:
a=np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([[4,3,2,1],[4,3,2,1]])

### Addition

In [10]:
a+2
np.add(a,2)
# Output :array([[3, 4, 5, 6],[3, 4, 5, 6]])
a+b
np.add(a,b)
# Output : array([[5, 5, 5, 5],[5, 5, 5, 5]])

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

### Subtraction

In [11]:
a-2
np.subtract(a,2)
# Ouptput : array([[-1,  0,  1,  2],[-1,  0,  1,  2]])
a-b
np.subtract(a,b)
# Output : array([[-3, -1,  1,  3],[-3, -1,  1,  3]])

array([[-3, -1,  1,  3],
       [-3, -1,  1,  3]])

### Element-Wise Multiply

In [12]:
a*2
np.multiply(a,2)
# Output : array([[2, 4, 6, 8],[2, 4, 6, 8]])
a*b
np.multiply(a,b)
# Output : array([[4, 6, 6, 4],[4, 6, 6, 4]])

array([[4, 6, 6, 4],
       [4, 6, 6, 4]])

### Division

In [13]:
a/2
np.divide(a,2)
# Output : array([[0.5, 1. , 1.5, 2. ],[0.5, 1. , 1.5, 2. ]])
a/b
np.divide(a,b)
# Output : array([[0.25 , 0.66666667, 1.5 , 4. ],[0.25 , 0.66666667, 1.5 , 4]])

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [0.25      , 0.66666667, 1.5       , 4.        ]])

### Floor Division

In [14]:
a//2
np.floor_divide(a,2)
# Output : array([[0, 1, 1, 2],[0, 1, 1, 2]])
a//b
np.floor_divide(a,b)
# Output : array([[0, 0, 1, 4],[0, 0, 1, 4]])

array([[0, 0, 1, 4],
       [0, 0, 1, 4]])

### Modulus

In [15]:
a%2
np.mod(a,2)
# Output : array([[1, 0, 1, 0],[1, 0, 1, 0]])
a%b
np.mod(a,b)
# Output : array([[1, 2, 1, 0],[1, 2, 1, 0]])

array([[1, 2, 1, 0],
       [1, 2, 1, 0]])

### Power

In [16]:
a**2
np.power(a,2)
# Output : array([[ 1,  4,  9, 16],[ 1,  4,  9, 16]])
a**b
np.power(a,b)
# Output : array([[1, 8, 9, 4],[1, 8, 9, 4]])

array([[1, 8, 9, 4],
       [1, 8, 9, 4]])

---
#### *Some Traps*

In [ ]:
a=np.array([1,3,5])
b=np.array([2,4,6,8])
c=np.array([2.2,3.3,4.4])
a+c

array([3.2, 6.3, 9.4])

In [ ]:
a+b 
c+b
# Error Cause of Different Shape

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
a+c # Int and Float operations are Possible

array([3.2, 6.3, 9.4])