# **Array**

In [4]:
import numpy as np

In [5]:
lst=[1,2,3,4]
arr=np.array(lst)
arr
type(arr)
arr.dtype

dtype('int64')

In [6]:
# lst=[]

# for i in range(5):
#     inp=int(input('Enter :'))
#     lst.append(inp)
# np.array(lst)

## **Types Of Array**
---

<img src="https://www.altexsoft.com/static/content-image/2024/10/a4b72e73-3b9d-48b1-b5ba-7451e10c43b2.png" alt="Numpy Array" width="700"/>

---

### **1D Array**

In [7]:
arr1D=np.array([1,2,3])
arr1D.ndim
arr1D.shape

(3,)

### **2D Array**


In [8]:
arr2D=np.array([[1,2,3],
                [1,2,3]])
arr2D.ndim
arr2D.shape

(2, 3)

### **3D Array**


In [9]:
arr3D=np.array([[[1,2,3],
                 [1,2,3],
                 [1,2,3]],
                 [[1,2,3],
                  [1,2,3],
                  [1,2,3]]])
arr3D.ndim
arr3D.shape

(2, 3, 3)

### **nD Array**


In [10]:
arrND=np.array([1,2,3],ndmin=6)
arrND.ndim
arrND.shape

(1, 1, 1, 1, 1, 3)

> While Creating Multiple Dimensional make sure all Arrays must be same size

---
## **Array Creation Functions**
### **Zeros Array**
```python
np.zeros((shape), dtype=float)
```


In [23]:
arr_zero=np.zeros((3,3,3))
arr_zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### **Ones Array**
```python
np.ones((shape), dtype=float)
```


In [25]:
arr_ones=np.ones((3,3,3))
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### **Empty Array**
```python
np.empty((shape), dtype=float)
```


In [27]:
arr_empty=np.empty((3,3,3))
arr_empty

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### **Array Range**
```python
np.arange(start, stop, step)
```


In [28]:
arr_range=np.arange(10)
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Identity Matrix**
```python
np.eye(N, M=None, k=0)
```
* (1s on diagonal, 0s elsewhere).
* `N` → number of rows
* `M` → number of columns (optional)
* `k` → diagonal index (0 = main diagonal)


In [36]:
arr_diagonal=np.eye(5,5)
arr_diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## **linspace**
##### Creates evenly spaced numbers over a fixed interval.
```python
np.linspace(start, stop, num=50)
```
* `start` → starting value
* `stop` → ending value (included)
* `num` → number of values (default 50)

In [37]:
arr_lin=np.linspace(0,10,num=5)
arr_lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])