# **Array**

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]
arr=np.array(lst)
arr
type(arr)
arr.dtype

dtype('int64')

In [3]:
# lst=[]

# for i in range(5):
#     inp=int(input('Enter :'))
#     lst.append(inp)
# np.array(lst)

## **Types Of Array**
---

<img src="https://www.altexsoft.com/static/content-image/2024/10/a4b72e73-3b9d-48b1-b5ba-7451e10c43b2.png" alt="Numpy Array" width="700"/>

---

### **1D Array**

In [4]:
arr1D=np.array([1,2,3])
arr1D.ndim
arr1D.shape

(3,)

### **2D Array**


In [5]:
arr2D=np.array([[1,2,3],
                [1,2,3]])
arr2D.ndim
arr2D.shape

(2, 3)

### **3D Array**


In [6]:
arr3D=np.array([[[1,2,3],
                 [1,2,3],
                 [1,2,3]],
                 [[1,2,3],
                  [1,2,3],
                  [1,2,3]]])
arr3D.ndim
arr3D.shape

(2, 3, 3)

### **nD Array**


In [7]:
arrND=np.array([1,2,3],ndmin=6)
arrND.ndim
arrND.shape

(1, 1, 1, 1, 1, 3)

> While Creating Multiple Dimensional make sure all Arrays must be same size

---
## **Array Creation Functions**
### **Zeros Array**
```python
np.zeros((shape), dtype=float)
```


In [8]:
arr_zero=np.zeros((3,3,3))
arr_zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### **Ones Array**
```python
np.ones((shape), dtype=float)
```


In [9]:
arr_ones=np.ones((3,3,3))
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### **Empty Array**
```python
np.empty((shape), dtype=float)
```


In [10]:
arr_empty=np.empty((3,3,3))
arr_empty

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### **Array Range**
```python
np.arange(start, stop, step)
```


In [11]:
arr_range=np.arange(10)
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Identity Matrix**
```python
np.eye(N, M=None, k=0)
```
* (1s on diagonal, 0s elsewhere).
* `N` → number of rows
* `M` → number of columns (optional)
* `k` → diagonal index (0 = main diagonal)


In [12]:
arr_diagonal=np.eye(5,5)
arr_diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **linspace**
##### Creates evenly spaced numbers over a fixed interval.
```python
np.linspace(start, stop, num=50)
```
* `start` → starting value
* `stop` → ending value (included)
* `num` → number of values (default 50)

In [13]:
arr_lin=np.linspace(0,10,num=5)
arr_lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

---
# **Practice Problems**

##### 1️⃣ Create this array **without typing numbers manually**

```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

Constraints:

* No list of lists
* Use **only one NumPy function**


In [14]:
arr=np.arange(1,10).reshape(3,3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### 2️⃣ Create a **1D array of size 10**

```
[0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
```

Constraints:

* No loops
* No manual repetition


In [89]:
np.linspace(0,4,num=10).astype(int)
np.repeat(np.arange(5),2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

##### 3️⃣ Create a **float array** of shape `(5,)`

```
[1. , 0.75, 0.5 , 0.25, 0.]
```

Constraints:

* Use `linspace` or `arange`
* Values must be exact


In [16]:
np.linspace(1,0,num=5)

array([1.  , 0.75, 0.5 , 0.25, 0.  ])

##### 4️⃣ Create this array using **broadcasting**

```
[[1 2 3]
 [1 2 3]
 [1 2 3]]
```

Constraints:

* No `tile`
* No loops

In [93]:
arr=np.ones(3,dtype='i')
arr2=np.array([[0],[1],[2]])
(arr2+arr).T

np.ones((3,1),dtype=int)*np.arange(1,4)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

##### 5️⃣ Create this array

```
[[1 1 1]
 [2 2 2]
 [3 3 3]]
```

Constraints:

* Use `reshape`
* Use broadcasting


In [97]:
arr=np.ones(3,dtype='i')
arr2=np.array([[0],[1],[2]])
arr+arr2

np.arange(1,4).reshape(3,1) * np.ones((1,3),dtype=int)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

##### 6️⃣ Create a **3×3 identity matrix**

But:

* Diagonal must be `5`
* Other values must be `-1`

Output:

```
[[ 5 -1 -1]
 [-1  5 -1]
 [-1 -1  5]]
```

In [ ]:
identity_mat=np.eye(3,3,k=0)
identity_mat[identity_mat==0]=-1
identity_mat[identity_mat==1]=5
identity_mat


np.eye(3,3,k=0)*6-1

array([[ 5., -1., -1.],
       [-1.,  5., -1.],
       [-1., -1.,  5.]])

##### 7️⃣ Create a `(4, 4)` array where:

* Each row is `[0, 1, 2, 3]`
* But dtype must be **float32**


In [ ]:
arr=np.array([[0,1,2,3]*4],dtype=np.float32).reshape(4,4)
arr


np.tile(np.arange(4, dtype=np.float32), (4, 1))


array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]], dtype=float32)

##### 8️⃣ Create this **checkerboard pattern**

```
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
```

Constraints:

* No loops
* No hardcoding


In [ ]:
checkerboard=np.zeros((4,4),dtype='int')
checkerboard[1::2,0::2]=1
checkerboard[0::2,1::2]=1
checkerboard

#OR 

np.indices((4,4)).sum(axis=0)%2

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

##### 9️⃣ Create a `(5, 5)` array where:

* Border values = `1`
* Inner values = `0`


In [68]:
ones=np.ones((5,5))
ones[1:4,1:4]=0
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### 🔟 Create a `(3, 5)` array such that:

```
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
```

Constraints:

* No loops
* Use broadcasting
* Use `arange` only **once**

In [108]:
arr=np.arange(0,5)
cols=[[0],[10],[20]]
arr+cols

# OR

np.arange(5)+np.arange(0,30,10).reshape(3,1)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

##### 1️⃣1️⃣ Create this array using **reshape + broadcasting**

```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

Constraints:

* Do NOT use `arange(1,10)`
* Do NOT use reshape directly on a 1D array


In [109]:
a=np.array([1,2,3])
b=np.array([0,3,6])
b=b.reshape(3,1)
a+b

# OR

(np.arange(9)+1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### 1️⃣2️⃣ Create a `(6, 6)` array where:

* Each row increases by `1`
* Each column increases by `10`

Example first row:

```
[0 1 2 3 4 5]
```

Second row:

```
[10 11 12 13 14 15]
```

In [110]:
a=np.arange(0,6)
b=np.arange(0,60,10).reshape(6,1)
a+b

# OR

np.arange(6)+np.arange(0,60,10).reshape(6,1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### 1️⃣3️⃣ Create a `(4, 4)` array where:

* Values increase row-wise
* Last column is always `-1`

In [ ]:
arr=np.arange(0,16).reshape(4,4)
arr[:,3:]=-1
arr

# OR

arr = np.arange(16).reshape(4, 4)
arr[:, -1] = -1
arr

array([[ 0,  1,  2, -1],
       [ 4,  5,  6, -1],
       [ 8,  9, 10, -1],
       [12, 13, 14, -1]])