# **Broadcasting**
##### Broadcasting allows NumPy to perform operations on arrays of different shapes.

Basic Syntax:
```python
result = array1 OP array2
```


`(OP = + - * / etc.)`

### Broadcasting Rules

* **Compare shapes from right to left**
* **Dimensions are compatible if they are equal OR one of them is `1`**
* **Shape Must be same of Arrays if Not then MUST have the same No of Cols OR the same No of Rows** 
* **Missing dimensions are treated as `1`**
* **Arrays are expanded virtually (no extra memory used)**
* **If rules fail → `ValueError`**

#### One-Line Memory Rule

    Broadcasting is fast and memory-efficient because NumPy does not copy data.

In [ ]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])

arr1+arr2

a=np.array([1,2,3]) # (1,3)
b=np.array([[1],[2],[3]]) # (3,1)
# (1,3) (3,1) : Following rule 3=3 OR 3=1
# new array will be 3x3 size
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## Scaler Broadcast

In [3]:
arr1+10

array([11, 12, 13, 14, 15])

## Row Broadcast
```text
arr (2,3)
row (3,)  → treated as (1, 3)
```
> **Dimensions are not equal but one of them is `1`**


> `row` have same Number of Columns as `arr`



In [16]:

arr=np.array([[3,3,3],
              [3,3,3],
              ])

row=np.array([1,1,1])

arr+row

array([[4, 4, 4],
       [4, 4, 4]])

## Column Broadcast
```text
arr (2,3)
cols (3,1)
```
> **Dimensions are not equal but one of them is `1`**

> `Cols` have same Number of rows as `arr`


In [ ]:
cols=np.array([[1],[1]])

arr+cols

array([[4, 4, 4],
       [4, 4, 4]])

---
#### **Invalid Broadcasting**

In [19]:
arr1=np.array([[3,3,3],[3,3,3],[3,3,3]])
arr2=np.array([[1,1,1],[1,1,1]])

# arr1+arr2 
# Output : ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 