# **Broadcasting**
##### Broadcasting allows NumPy to perform operations on arrays of different shapes.

Basic Syntax:
```python
result = array1 OP array2
```


`(OP = + - * / etc.)`

### Broadcasting Rules

* **Compare shapes from right to left**
* **Dimensions are compatible if they are equal OR one of them is `1`**
* **Shape Must be same of Arrays if Not then MUST have the same No of Cols OR the same No of Rows** 
* **Missing dimensions are treated as `1`**
* **Arrays are expanded virtually (no extra memory used)**
* **If rules fail → `ValueError`**

#### One-Line Memory Rule

    Broadcasting is fast and memory-efficient because NumPy does not copy data.

In [102]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])

arr1+arr2

a=np.array([1,2,3]) # (1,3)
b=np.array([[1],[2],[3]]) # (3,1)
# (1,3) (3,1) : Following rule 3=3 OR 3=1
# new array will be 3x3 size
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## Scaler Broadcast

In [103]:
arr1+10

array([11, 12, 13, 14, 15])

## Row-Wise Broadcast
```text
arr (2,3)
row (3,)  → treated as (1, 3)
```
> **Dimensions are not equal but one of them is `1`**


> `row` have same Number of Columns as `arr`



In [104]:

arr=np.array([[3,3,3],
              [3,3,3],
              ])

row=np.array([1,1,1])

arr+row

array([[4, 4, 4],
       [4, 4, 4]])

## Column-Wise Broadcast
```text
arr (2,3)
cols (3,1)
```
> **Dimensions are not equal but one of them is `1`**

> `Cols` have same Number of rows as `arr`


In [105]:
cols=np.array([[1],[1]])

arr+cols

array([[4, 4, 4],
       [4, 4, 4]])

---
#### **Invalid Broadcasting**

In [106]:
arr1=np.array([[3,3,3],[3,3,3],[3,3,3]])
arr2=np.array([[1,1,1],[1,1,1]])

# arr1+arr2 
# Output : ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

---
# **Practice Problems**

##### 1️⃣

Create a **6×6** matrix where:

```
M[i][j] = i + j
```

📌 Use **two 1D arrays only**

In [ ]:
a=np.array([10,11,12,13,14,15])
b=np.array([2,3,4,5,6,7]).reshape(6,1)
a+b

array([[12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20],
       [16, 17, 18, 19, 20, 21],
       [17, 18, 19, 20, 21, 22]])

##### 2️⃣

Create a **5×5** matrix where:

* Rows increase by `1`
* Columns increase by `10`
* Starting value = `5`

📌 No hard-coded matrices

In [150]:
rows=np.arange(5,10).reshape(5,1)
cols=np.arange(0,50,10)
rows+cols

# OR
M = 5 + rows + cols*10
M

array([[ 10, 110, 210, 310, 410],
       [ 11, 111, 211, 311, 411],
       [ 12, 112, 212, 312, 412],
       [ 13, 113, 213, 313, 413],
       [ 14, 114, 214, 314, 414]])

##### 3️⃣

Given:

```python
A = np.arange(1, 7)
```

Create:

```
[[ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]]
```

In [158]:
A=np.arange(1,7)
ones=np.arange(6).reshape(6,1)
A+ones

# OR
M=A+np.arange(6).reshape(6,1)
M


array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11]])


##### 4️⃣

Create a **4×4** matrix where:

```
M[i][j] = (i+1) × (j+1)
```

📌 No loops

In [110]:
i=np.arange(5)
j=np.arange(5).reshape(5,1)
i[1:]*j[1:]

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

##### 5️⃣

Given:

```python
x = np.array([1, 2, 3])
y = np.array([10, 20, 30, 40])
```

Create a matrix:

```
[[11, 21, 31, 41],
 [12, 22, 32, 42],
 [13, 23, 33, 43]]
```


In [111]:
x=np.array([1,2,3]).reshape(3,1)
y=np.array([10,20,30,40])
x+y


array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

##### 6️⃣

Create a **7×7** matrix where:

* Main diagonal = `0`
* Upper triangle = `1`
* Lower triangle = `-1`

📌 Broadcasting + masking only

In [114]:
n=7
mat=np.full((n,n),1)
mat[np.tril_indices(n,-1)]=-1
mat[np.diag_indices(n)]=0
mat

array([[ 0,  1,  1,  1,  1,  1,  1],
       [-1,  0,  1,  1,  1,  1,  1],
       [-1, -1,  0,  1,  1,  1,  1],
       [-1, -1, -1,  0,  1,  1,  1],
       [-1, -1, -1, -1,  0,  1,  1],
       [-1, -1, -1, -1, -1,  0,  1],
       [-1, -1, -1, -1, -1, -1,  0]])

In [161]:
# OR
i, j = np.indices((7,7))
M = np.where(i == j, 0, np.where(i < j, 1, -1))
M

array([[ 0,  1,  1,  1,  1,  1,  1],
       [-1,  0,  1,  1,  1,  1,  1],
       [-1, -1,  0,  1,  1,  1,  1],
       [-1, -1, -1,  0,  1,  1,  1],
       [-1, -1, -1, -1,  0,  1,  1],
       [-1, -1, -1, -1, -1,  0,  1],
       [-1, -1, -1, -1, -1, -1,  0]])

##### 7️⃣

Given:

```python
arr = np.arange(5)
```

Create a **5×5** matrix where:

```
M[i][j] = arr[i] * arr[j]
```

In [117]:
arr=np.arange(5)
arr*arr.reshape(5,1)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

##### 8️⃣

Create a matrix where:

```
M[i][j] = |i − j|
```

Size = **8×8**

In [ ]:
i=np.arange(8)
j=np.arange(8).reshape(8,1)
np.abs(i-j)

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 0, 1, 2, 3, 4, 5, 6],
       [2, 1, 0, 1, 2, 3, 4, 5],
       [3, 2, 1, 0, 1, 2, 3, 4],
       [4, 3, 2, 1, 0, 1, 2, 3],
       [5, 4, 3, 2, 1, 0, 1, 2],
       [6, 5, 4, 3, 2, 1, 0, 1],
       [7, 6, 5, 4, 3, 2, 1, 0]])

##### 9️⃣

Create a **checkerboard** where:

* Even rows → `[0 1 0 1 ...]`
* Odd rows → `[1 0 1 0 ...]`
  Size = **6×6**

📌 Broadcasting required


In [166]:
checkerboad=np.zeros((6,6))
checkerboad[1::2,0::2]=1
checkerboad[0::2,1::2]=1
checkerboad

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

In [169]:
# OR
i, j = np.indices((6,6))
checkerboard = (i + j) % 2
checkerboad

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

##### 🔟

Create a **5×5** matrix where:

```
Row i = [i, i², i³, i⁴, i⁵]
```

📌 No loops


In [173]:
arr=np.arange(1,6).reshape(5,1)
pw=np.array([1,2,3,4,5])
arr**pw


array([[   1,    1,    1,    1,    1],
       [   2,    4,    8,   16,   32],
       [   3,    9,   27,   81,  243],
       [   4,   16,   64,  256, 1024],
       [   5,   25,  125,  625, 3125]])

##### 1️⃣1️⃣

Given:

```python
x = np.arange(1, 6)
```

Create:

```
[[ x1/x1, x2/x1, x3/x1, ...],
 [ x1/x2, x2/x2, x3/x2, ...],
 ...
]
```

In [ ]:
x=np.arange(1,6)
x/x.reshape(5,1)

array([[1.        , 2.        , 3.        , 4.        , 5.        ],
       [0.5       , 1.        , 1.5       , 2.        , 2.5       ],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
       [0.25      , 0.5       , 0.75      , 1.        , 1.25      ],
       [0.2       , 0.4       , 0.6       , 0.8       , 1.        ]])

##### 1️⃣2️⃣

Create a **9×9** matrix where:

* Each row is a **right-shifted version** of `[1,2,3,4,5,6,7,8,9]`
* Shifts increase row-wise

📌 Broadcasting only (no roll/loops)


In [143]:
columns=np.arange(1,10)
rows=np.arange(1,10).reshape(9,1)
result=((columns-rows)%9)+1
result

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 1, 2, 3, 4, 5, 6, 7, 8],
       [8, 9, 1, 2, 3, 4, 5, 6, 7],
       [7, 8, 9, 1, 2, 3, 4, 5, 6],
       [6, 7, 8, 9, 1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9, 1, 2, 3, 4],
       [4, 5, 6, 7, 8, 9, 1, 2, 3],
       [3, 4, 5, 6, 7, 8, 9, 1, 2],
       [2, 3, 4, 5, 6, 7, 8, 9, 1]])

In [180]:
base = np.arange(1,10)
shifts = np.arange(9).reshape(9,1)
M = np.where(np.arange(9) >= shifts, base[np.arange(9)-shifts], 0)
M


array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 0, 1, 2, 3, 4, 5, 6, 7],
       [0, 0, 0, 1, 2, 3, 4, 5, 6],
       [0, 0, 0, 0, 1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0, 0, 1, 2, 3],
       [0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

#####  1️⃣3️⃣

Create a **10×10** matrix where:

```
M[i][j] = (i+1)^(j+1)
```

📌 Pure broadcasting
📌 No loops
📌 No tile/repeat



In [181]:
cols=np.arange(1,11)
rows=np.arange(1,11).reshape(10,1)
rows**cols

array([[          1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1],
       [          2,           4,           8,          16,          32,
                 64,         128,         256,         512,        1024],
       [          3,           9,          27,          81,         243,
                729,        2187,        6561,       19683,       59049],
       [          4,          16,          64,         256,        1024,
               4096,       16384,       65536,      262144,     1048576],
       [          5,          25,         125,         625,        3125,
              15625,       78125,      390625,     1953125,     9765625],
       [          6,          36,         216,        1296,        7776,
              46656,      279936,     1679616,    10077696,    60466176],
       [          7,          49,         343,        2401,       16807,
             117649,      823543,     5764801