# **Copy**

#### A copy duplicates the data into new memory.

In [ ]:
import numpy as np

arr=np.array([1,2,3])

copyOfArr=arr.copy()
copyOfArr[0]=999
copyOfArr


array([1, 2, 3])

Common operations that return Copy

| Operation                   |
| --------------------------- |
| `copy()`                    |
| `flatten()`                 |
| Fancy indexing `a[[0,2]]`   |
| Boolean indexing `a[a > 2]` |


In [14]:
arr.flatten()

arr[[0,1]]

arr[arr>1]

array([2, 3])

# **View**

#### A view is just another way of looking at the same data in memory.

In [20]:
arr=np.array([1,2,3,4,5,6])

viewOfArr=arr.view()
viewOfArr[0]=999
arr


array([999,   2,   3,   4,   5,   6])

Common operations that return views

| Operation             |
| --------------------- |
| `reshape()` (usually) |
| `ravel()` (usually)   |
| Slicing `a[1:4]`      |
| `transpose()`         |
| `diagonal()` ⚠️       |


In [26]:
arr.reshape(-1,1)
arr.ravel()
arr[:-1]

mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat.T

mat.diagonal()

array([1, 5, 9])