# **Math Functions**

In [1]:
import numpy as np
arr=np.array([2,4,6,8,10])

## **Square Root**

In [2]:
np.sqrt(arr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

## **Absolute Value**

In [3]:
np.abs(arr)

array([ 2,  4,  6,  8, 10])

## **Power**

In [4]:
np.power(arr,2)

array([  4,  16,  36,  64, 100])

## **Exponential**

In [5]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

## **Natural Log**

In [6]:
np.log(arr)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

## **Sine**

In [7]:
np.sin(arr)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111])

## **Cosine**

In [8]:
np.cos(arr)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153])

## **Tangent**

In [9]:
np.tan(arr)

array([-2.18503986,  1.15782128, -0.29100619, -6.79971146,  0.64836083])

---
# **Practice Problems**

##### 1️⃣ Sine & Cosine Table

Create a **2D array** `angles` of shape `(5,5)` where:

* Values = `[0, π/4, π/2, 3π/4, π]` repeated row-wise
* Compute **sin²(angle) + cos²(angle)** for each element
* Verify it equals 1


In [80]:
angles=np.array([0,np.pi/4,np.pi/2,3*np.pi/4,np.pi]*5).reshape((5,5))
np.power(np.sin(angles),2) + np.power(np.cos(angles),2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### 2️⃣ Sum of powers

Create a `(5,5)` array `A = np.arange(1,26).reshape(5,5)`
Compute:

```
A² + A³
```

❌ Do NOT use loops


In [11]:
A=np.arange(1,26).reshape(5,5)
np.power(A,2) + np.power(A,3)

array([[    2,    12,    36,    80,   150],
       [  252,   392,   576,   810,  1100],
       [ 1452,  1872,  2366,  2940,  3600],
       [ 4352,  5202,  6156,  7220,  8400],
       [ 9702, 11132, 12696, 14400, 16250]])


##### 3️⃣ Angle conversion

Given degrees array:

```python
deg = np.array([0, 30, 45, 60, 90])
```

* Convert to radians
* Compute **tan**
* Round to 2 decimals


In [83]:
deg=np.array([0,30,45,60,90])
radians=np.deg2rad(deg)
np.round(np.tan(radians),2)

array([0.00000000e+00, 5.80000000e-01, 1.00000000e+00, 1.73000000e+00,
       1.63312394e+16])

In [85]:
np.round(np.tan(np.radians(deg)),2)

array([0.00000000e+00, 5.80000000e-01, 1.00000000e+00, 1.73000000e+00,
       1.63312394e+16])

##### 4️⃣ Normalize via log

Given:

```python
arr = np.array([10, 100, 1000, 10000])
```

* Apply **log base 10**
* Subtract **min(log10(arr))**
* Divide by **max(log10(arr))**
* Output between 0 and 1

In [89]:
arr=np.array([10,100,1000,10000])
log_arr=np.log10(arr)
normalized=(log_arr -log_arr.min())/log_arr.max()
normalized

array([0.  , 0.25, 0.5 , 0.75])

##### 5️⃣ Exponential scaling

Given:

```python
x = np.arange(1,6)
```

Compute:

```
y = e^(2x) - e^x
```

* Use **np.exp**
* Output as float64


In [14]:
x=np.arange(1,6)
y=np.exp(2*x) - np.exp(x)
y

array([4.67077427e+00, 4.72090939e+01, 3.83343257e+02, 2.92635984e+03,
       2.18780526e+04])

##### 6️⃣ Row-wise statistics

Given:

```python
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
```

Compute **row-wise**:

* sqrt(sum(row²)) → Euclidean norm
* Use **np.sqrt**, **np.sum**, **axis parameter**


In [90]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sqrt(np.sum(A**2,axis=1))

array([ 3.74165739,  8.77496439, 13.92838828])

##### 7️⃣ Conditional function

Given:

```python
arr = np.linspace(-5,5,11)
```

* Apply:

```
f(x) = sin(x) if x > 0 else cos(x)
```

* Use **vectorized np.where**


In [16]:
arr=np.linspace(-5,5,11)
np.where(arr>0,np.sin(arr),np.cos(arr))

array([ 0.28366219, -0.65364362, -0.9899925 , -0.41614684,  0.54030231,
        1.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

##### 8️⃣ Hypotenuse matrix

Create `(3,3)` arrays:

```python
X = np.arange(1,4).reshape(3,1)
Y = np.arange(1,4)
```

* Compute `hypotenuse = sqrt(X² + Y²)` for each element


In [18]:
X=np.arange(1,4).reshape(3,1)
Y=np.arange(1,4)

hypotenues=np.sqrt(X**2 + Y**2)
hypotenues

array([[1.41421356, 2.23606798, 3.16227766],
       [2.23606798, 2.82842712, 3.60555128],
       [3.16227766, 3.60555128, 4.24264069]])

### 9️⃣ Checkerboard sin-cos

Create `(4,4)` array where:

```
even indices → sin(i+j)
odd indices → cos(i+j)
```

* Use **np.indices**, **np.where**, vectorized functions


In [91]:
i,j=np.indices((4,4))
np.where((i+j)%2==0,np.sin(i+j),np.cos(i+j))

array([[ 0.        ,  0.54030231,  0.90929743, -0.9899925 ],
       [ 0.54030231,  0.90929743, -0.9899925 , -0.7568025 ],
       [ 0.90929743, -0.9899925 , -0.7568025 ,  0.28366219],
       [-0.9899925 , -0.7568025 ,  0.28366219, -0.2794155 ]])

##### 🔟 Exponential decay

Simulate decay over 5 time steps:

```python
x0 = np.array([100, 200, 300])
k = 0.1
t = np.arange(5)
```

* Compute:

```
x(t) = x0 * exp(-k * t)
```

* Output shape = `(3,5)`
* Broadcasting required


In [31]:
x0=np.array([100,200,300]).reshape(3,1)
k=0.1
t=np.arange(5)
x_t=x0*np.exp(-k *t)
x_t

array([[100.        ,  90.4837418 ,  81.87307531,  74.08182207,
         67.0320046 ],
       [200.        , 180.96748361, 163.74615062, 148.16364414,
        134.06400921],
       [300.        , 271.45122541, 245.61922592, 222.2454662 ,
        201.09601381]])


##### 1️⃣1️⃣ Logarithmic difference

Given:

```python
arr = np.array([10, 100, 1000, 10000])
```

* Compute:

```
diffs[i] = log(arr[i+1]) - log(arr[i])
```

* Result shape = `(len(arr)-1,)`
* Use **np.log** and vectorization


In [ ]:
arr=np.array([10,100,1000,10000])
diffs_i=np.log(arr[1:]) - np.log(arr[:-1])
diffs_i

3

##### 1️⃣2️⃣ Combined function

Given `arr = np.arange(1,6)` compute:

```
y = sqrt(arr) + sin(arr) - log(arr)
```

* Output as **float32**


In [98]:
arr=np.arange(1,6)
y=(np.sqrt(arr) + np.sin(arr) - np.log(arr)).astype(np.float32)
y

array([ 1.841471  ,  1.6303638 ,  0.77455854, -0.14309685, -0.3322942 ],
      dtype=float32)

##### 1️⃣3️⃣ Normalize trigonometry

Create `(6,)` array of angles `[0,30,60,...,150]` in degrees

* Convert to radians
* Compute **sin**
* Scale results between 0 and 1

In [103]:
deg=np.arange(0,180,30)
radians=np.radians(deg)
sin=np.sin(radians)
normalized=(sin-sin.min())/(sin.max()-sin.min())
normalized

array([0.       , 0.5      , 0.8660254, 1.       , 0.8660254, 0.5      ])

In [104]:
sin

array([0.       , 0.5      , 0.8660254, 1.       , 0.8660254, 0.5      ])