# **Math Functions**

In [ ]:
import numpy as np
arr=np.array([2,4,6,8,10])

## **Square Root**

In [2]:
np.sqrt(arr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

## **Absolute Value**

In [3]:
np.abs(arr)

array([ 2,  4,  6,  8, 10])

## **Power**

In [5]:
np.power(arr,2)

array([  4,  16,  36,  64, 100])

## **Exponential**

In [6]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

## **Natural Log**

In [7]:
np.log(arr)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

## **Sine**

In [8]:
np.sin(arr)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111])

## **Cosine**

In [9]:
np.cos(arr)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153])

## **Tangent**

In [10]:
np.tan(arr)

array([-2.18503986,  1.15782128, -0.29100619, -6.79971146,  0.64836083])