# **Random Functions**

In [4]:
import numpy as np

# All random functions live inside:
# np.random


## **`rand()`** 
* Generates **random floats between 0 and 1**
* Uniform Distribution
* Values are in **[0.0, 1.0]**

```python
np.random.rand(d0,d1,...dn)
```
`d0, d1,...` -> Dimensions (No Tuple Pass Directly)


In [17]:
np.random.rand(3)
np.random.rand(3,3)
np.random.rand(3,3,3)

array([[[0.10154739, 0.07396375, 0.65005458],
        [0.9647178 , 0.6306875 , 0.87436747],
        [0.61549353, 0.33541442, 0.75976596]],

       [[0.37753456, 0.1624247 , 0.28944489],
        [0.07898437, 0.77022486, 0.17142938],
        [0.37616111, 0.90841248, 0.88418823]],

       [[0.774932  , 0.42463754, 0.29256641],
        [0.19854516, 0.5736248 , 0.17786267],
        [0.35826621, 0.38804038, 0.055464  ]]])

## **`randn()`**

* Generates random numbers from **standard normal distribution**
* Mean ≈ `0`, Standard Deviation ≈ `1`
* Can return **Positive or Negative (Close to Zero)** values

```python
np.random.randn(d0,d1,...dn)
```
`d0, d1,...` -> Dimensions (No Tuple Pass Directly)

In [ ]:
np.random.randn(3)
np.random.randn(3,3)
np.random.randn(3,3,3)

array([[[-1.41922888, -0.9440945 , -0.35371478],
        [ 0.92680683,  1.73113013, -0.30299285],
        [ 1.70352759, -0.40971805, -0.46694987]],

       [[ 0.28785588, -0.40144735,  0.83940951],
        [ 0.51715798, -0.66776188, -0.31081125],
        [ 1.20965036,  0.89399438, -1.34617541]],

       [[-0.67639506,  1.19799432,  0.205791  ],
        [ 0.86343456, -0.42298412, -1.05992541],
        [ 0.13823652, -0.28984398,  0.34571102]]])

## **`ranf()`**

* Generates random floats in **[0.0, 1.0]**
* Similar to **`rand()`**, but accepts **shape as a tuple**
```python
np.random.ranf(size=None)
```
`size` → int or tuple (array shape)
#### **`np.random.random(size=())`** is also same

In [ ]:
np.random.ranf(3)
np.random.ranf((3,3))
np.random.ranf((3,3,3))

array([[[0.53999193, 0.37986852, 0.98569924],
        [0.05388009, 0.93869095, 0.36082523],
        [0.25717992, 0.01466481, 0.40112471]],

       [[0.23919711, 0.97187413, 0.47924687],
        [0.90073909, 0.40051726, 0.14770213],
        [0.03732278, 0.21112046, 0.47798268]],

       [[0.53264175, 0.65902455, 0.26552798],
        [0.50664426, 0.77367513, 0.98261432],
        [0.03940432, 0.6552986 , 0.16406788]]])

## **`randint()`**

* Generates **random integers** in a given range
* Lower bound **included**, upper bound **excluded**

```python
np.random.randint(low, high=None, size=None, dtype=int)
```
`low` → minimum value (inclusive)

`high` → maximum value (exclusive)

`size` → number or shape of output

`dtype` → data type (optional)

In [27]:
np.random.randint(1,10)
np.random.randint(1,10,5)
np.random.randint(1,10,(3,3))




array([[7, 2, 6],
       [2, 9, 6],
       [2, 5, 5]], dtype=int32)

## **`choice()`**
* Randomly select values from an array
```python
np.random.random([],size=None)
```

In [34]:
np.random.choice([1,2,3],size=2)

array([2, 1])

## **`shuffle()`**
* Shuffles array **in-place**
```python
np.random.shuffle(array)
```

In [ ]:
arr=np.array([1,2,3,4])
np.random.shuffle(arr)

array([4, 2, 1, 3])

## **`permutation()`**
* Returns a **shuffled copy**
```python
np.random.permutation(arr)
```

In [38]:
np.random.permutation(arr)

array([4, 3, 2, 1])

## **`seed()`**
* Sets seed for **reproducibility**
* Fixes the random number generator
* Ensures **same output every time** (reproducibility)
```python
np.random.seed(n)
```


In [43]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

## **`normal()`**
* Generates numbers from **Normal (Gaussian) distribution**
* Mean = `loc`, Standard deviation = `scale`
```python
np.random.normal(loc=0.0, scale=1.0, size=None)
```
📌 Used in ML, statistics, noise simulation.

In [46]:
np.random.seed(42)
np.random.normal(size=5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

## **`uniform()`**
* Generates numbers **uniformly distributed**
* All values have equal probability
```python
np.random.uniform(low=0.0, high=1.0, size=None)
```
📌 Used when no bias is assumed.

In [47]:
np.random.seed(42)
np.random.uniform(1, 10, 5)

array([4.37086107, 9.55642876, 7.58794548, 6.38792636, 2.40416776])

## **`binomial()`**
* Simulates **binary outcomes** (success / failure)
* Used in **Bernoulli trials**
```python
np.random.binomial(n, p, size=None)
```
`n` → number of trials

`p` → probability of success

`size` → output shape

📌 Used in A/B testing, coin tosses, experiments.

In [48]:
np.random.seed(42)
np.random.binomial(n=10, p=0.5, size=5)

array([4, 8, 6, 5, 3], dtype=int32)

## **`poisson()`**
* Model **Event counts over a fixed interval** 
* Used for **rare events**
```python
np.random.poisson(lam=1.0 size=None)
```
`lam` → average number of events

`size` → output shape

📌 Used for
* Calls per hour
* Accidents per day
* Server requests

In [49]:
np.random.seed(42)
np.random.poisson(lam=3, size=5)

array([4, 1, 3, 3, 2], dtype=int32)