# **Random Functions**

In [1]:
import numpy as np

# All random functions live inside:
# np.random


## **`rand()`** 
* Generates **random floats between 0 and 1**
* Uniform Distribution
* Values are in **[0.0, 1.0]**

```python
np.random.rand(d0,d1,...dn)
```
`d0, d1,...` -> Dimensions (No Tuple Pass Directly)


In [2]:
np.random.rand(3)
np.random.rand(3,3)
np.random.rand(3,3,3)

array([[[0.87782754, 0.33771869, 0.86838387],
        [0.72905294, 0.48432718, 0.1201982 ],
        [0.85991101, 0.56319311, 0.56553428]],

       [[0.63520058, 0.62334947, 0.23732775],
        [0.1120558 , 0.52225089, 0.13785681],
        [0.84068125, 0.33121058, 0.15054147]],

       [[0.77478793, 0.59610654, 0.31549559],
        [0.05780296, 0.87231339, 0.62192729],
        [0.10044535, 0.40049171, 0.72914126]]])

## **`randn()`**

* Generates random numbers from **standard normal distribution**
* Mean ≈ `0`, Standard Deviation ≈ `1`
* Can return **Positive or Negative (Close to Zero)** values

```python
np.random.randn(d0,d1,...dn)
```
`d0, d1,...` -> Dimensions (No Tuple Pass Directly)

In [3]:
np.random.randn(3)
np.random.randn(3,3)
np.random.randn(3,3,3)

array([[[-0.53495501, -0.32345191, -0.97817574],
        [-1.24343396, -0.72638199, -2.19767864],
        [ 0.61176664, -0.13147778, -2.78843521]],

       [[ 1.11147012,  0.12826458, -0.17320064],
        [ 0.83083699, -1.93441892,  0.16714226],
        [ 0.64819326, -0.20136579,  0.92088003]],

       [[ 2.31401098,  1.02340606, -0.03627859],
        [-0.72058154, -0.70094848,  1.34936371],
        [ 1.13183531, -0.10371707, -1.31708325]]])

## **`ranf()`**

* Generates random floats in **[0.0, 1.0]**
* Similar to **`rand()`**, but accepts **shape as a tuple**
```python
np.random.ranf(size=None)
```
`size` → int or tuple (array shape)
#### **`np.random.random(size=())`** is also same

In [4]:
np.random.ranf(3)
np.random.ranf((3,3))
np.random.ranf((3,3,3))

array([[[0.72857831, 0.76990868, 0.15435191],
        [0.23020038, 0.71686348, 0.14984167],
        [0.29610255, 0.79037743, 0.20440977]],

       [[0.43110919, 0.11407581, 0.63082524],
        [0.82976732, 0.23544791, 0.04172159],
        [0.06573713, 0.40030255, 0.38189784]],

       [[0.78812404, 0.67130808, 0.54844851],
        [0.31883723, 0.39123185, 0.15473161],
        [0.46226272, 0.47503931, 0.67982903]]])

## **`randint()`**

* Generates **random integers** in a given range
* Lower bound **included**, upper bound **excluded**

```python
np.random.randint(low, high=None, size=None, dtype=int)
```
`low` → minimum value (inclusive)

`high` → maximum value (exclusive)

`size` → number or shape of output

`dtype` → data type (optional)

In [5]:
np.random.randint(1,10)
np.random.randint(1,10,5)
np.random.randint(1,10,(3,3))




array([[7, 5, 3],
       [4, 5, 3],
       [1, 6, 4]], dtype=int32)

## **`choice()`**
* Randomly select values from an array
```python
np.random.random([],size=None)
```

In [6]:
np.random.choice([1,2,3],size=2)

array([2, 3])

## **`shuffle()`**
* Shuffles array **in-place**
```python
np.random.shuffle(array)
```

In [7]:
arr=np.array([1,2,3,4])
np.random.shuffle(arr)

## **`permutation()`**
* Returns a **shuffled copy**
```python
np.random.permutation(arr)
```

In [8]:
np.random.permutation(arr)

array([2, 1, 4, 3])

## **`seed()`**
* Sets seed for **reproducibility**
* Fixes the random number generator
* Ensures **same output every time** (reproducibility)
```python
np.random.seed(n)
```


In [9]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

## **`normal()`**
* Generates numbers from **Normal (Gaussian) distribution**
* Mean = `loc`, Standard deviation = `scale`
```python
np.random.normal(loc=0.0, scale=1.0, size=None)
```
📌 Used in ML, statistics, noise simulation.

In [10]:
np.random.seed(42)
np.random.normal(size=5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

## **`uniform()`**
* Generates numbers **uniformly distributed**
* All values have equal probability
```python
np.random.uniform(low=0.0, high=1.0, size=None)
```
📌 Used when no bias is assumed.

In [11]:
np.random.seed(42)
np.random.uniform(1, 10, 5)

array([4.37086107, 9.55642876, 7.58794548, 6.38792636, 2.40416776])

## **`binomial()`**
* Simulates **binary outcomes** (success / failure)
* Used in **Bernoulli trials**
```python
np.random.binomial(n, p, size=None)
```
`n` → number of trials

`p` → probability of success

`size` → output shape

📌 Used in A/B testing, coin tosses, experiments.

In [12]:
np.random.seed(42)
np.random.binomial(n=10, p=0.5, size=5)

array([4, 8, 6, 5, 3], dtype=int32)

## **`poisson()`**
* Model **Event counts over a fixed interval** 
* Used for **rare events**
```python
np.random.poisson(lam=1.0 size=None)
```
`lam` → average number of events

`size` → output shape

📌 Used for
* Calls per hour
* Accidents per day
* Server requests

In [13]:
np.random.seed(42)
np.random.poisson(lam=3, size=5)

array([4, 1, 3, 3, 2], dtype=int32)

---
# **Practice Problems**

##### 1️⃣ Reproducible random matrix

* Set seed = `42`
* Generate a **4×4** matrix from **uniform distribution [0,1)**
* Replace:

  * values `< 0.3` → `0`
  * values `>= 0.3` → `1`


In [153]:
np.random.seed(42)
arr=np.random.uniform(0,1,size=(4,4))
arr[arr>=0.3]=1
arr[arr<0.3]=0
arr.astype(int)

# OR
result=(arr>=0.3).astype(int)
result


array([[1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 0]])

##### 2️⃣ Normal distribution filtering

Generate **1000 samples** from a **normal distribution**:

* mean = `50`
* std = `10`
* Keep **only values between 40 and 60**
* Return the **count** of remaining values


In [167]:
np.random.seed(42)
samples=np.random.normal(50,10,1000)
samples=samples[(samples>=40)&(samples<=60)]
np.count_nonzero(samples)

# OR
filtered_count = np.sum((samples >= 40) & (samples <= 60))
filtered_count

np.int64(698)

##### 3️⃣ Random integers with pattern

Generate a **5×5** matrix of random integers between `1` and `9`

* Replace diagonal values with `0`
* Keep everything vectorized


In [16]:
np.random.seed(42)
arr=np.random.randint(1,9,(5,5))
np.fill_diagonal(arr,0)
arr

array([[0, 4, 5, 7, 3],
       [8, 0, 5, 7, 2],
       [3, 7, 0, 3, 8],
       [5, 4, 8, 0, 3],
       [6, 5, 2, 8, 0]], dtype=int32)

#### 4️⃣ Row-wise random scaling

* Generate a `(3,5)` random matrix from `uniform(0,1)`
* Multiply:

  * row 0 → ×10
  * row 1 → ×100
  * row 2 → ×1000
    📌 Broadcasting required


In [168]:
np.random.seed(42)
arr=np.random.uniform(0,1,(3,5))
cols=np.array([[10],[100],[1000]])
arr*cols

array([[  3.74540119,   9.50714306,   7.31993942,   5.98658484,
          1.5601864 ],
       [ 15.59945203,   5.80836122,  86.61761458,  60.11150117,
         70.80725778],
       [ 20.5844943 , 969.90985216, 832.4426408 , 212.33911068,
        181.82496721]])

##### 5️⃣ Binomial experiment

Simulate **1000 coin tosses** where:

* probability of success = `0.6`
* Each experiment has `10` trials
  Return:
* mean
* variance


In [169]:
toss=np.random.binomial(n=10,p=0.6,size=1000)
mean=np.mean(toss)
variance=np.var(toss)


##### 6️⃣ Poisson traffic simulation

Simulate **24 hours of traffic** using Poisson distribution:

* λ = `20`
* Identify **peak hours** where traffic > mean traffic


In [179]:
np.random.seed(42)
trafic=np.random.poisson(lam=20,size=24)
indices=np.where(trafic>np.mean(trafic))
trafic[indices]
indices

array([23, 21, 25, 19, 21, 19, 21, 21, 22, 21, 21, 25], dtype=int32)

##### 7️⃣ Uniform vs Normal comparison

Generate:

* 1000 samples from `uniform(0,1)`
* 1000 samples from `normal(0,1)`
  Compute:
* mean
* standard deviation
  Compare numerically (no plots)


In [181]:
np.random.seed(42)
uniform_dist=np.random.uniform(0,1,1000)
normal_dist=np.random.normal(0,1,1000)
uniform_dist_mean=np.mean(uniform_dist)
uniform_dist_std=np.std(uniform_dist)
normal_dist_mean=np.mean(normal_dist)
normal_dist_std=np.std(normal_dist)

print(f"Uniform Dist Mean :{uniform_dist_mean} and Standard Deviation :{uniform_dist_std}")
print(f"Normal Dist Mean :{normal_dist_mean} and Standard Deviation :{normal_dist_std}")


(np.float64(0.4902565533201336), np.float64(0.291991256731072))

##### 8️⃣ Random choice with probability

From array:

```python
choices = np.array([10, 20, 30, 40])
```

* Randomly select **1000 values**
* Probabilities = `[0.1, 0.2, 0.3, 0.4]`
* Count frequency of each value


In [187]:
np.random.seed(42)
choices=np.array([10,20,30,40])
arr=np.random.choice(choices,1000,p=[0.1,0.2,0.3,0.4])
np.unique_counts(arr)
# OR
np.unique(arr,return_counts=True)

(array([10, 20, 30, 40]), array([108, 211, 294, 387]))

##### 9️⃣ Random mask sampling

Generate a `(6,6)` matrix from `rand()`

* Create a boolean mask where values > `0.7`
* Replace masked values with `-1`


In [77]:
np.random.seed(42)
arr=np.random.rand(6,6)
arr[arr>0.7]=-1
arr

array([[ 0.37454012, -1.        , -1.        ,  0.59865848,  0.15601864,
         0.15599452],
       [ 0.05808361, -1.        ,  0.60111501, -1.        ,  0.02058449,
        -1.        ],
       [-1.        ,  0.21233911,  0.18182497,  0.18340451,  0.30424224,
         0.52475643],
       [ 0.43194502,  0.29122914,  0.61185289,  0.13949386,  0.29214465,
         0.36636184],
       [ 0.45606998, -1.        ,  0.19967378,  0.51423444,  0.59241457,
         0.04645041],
       [ 0.60754485,  0.17052412,  0.06505159, -1.        , -1.        ,
        -1.        ]])

##### 🔟 Monte Carlo π estimation

Use **random sampling** to estimate π:

* Generate 1,000,000 random points
* Points inside unit circle
  📌 No loops
  📌 Pure NumPy


In [193]:
np.random.seed(42)
x= np.random.rand(1000000)
y= np.random.rand(1000000)
r=x**2+y**2
count=np.sum(r<=1.0)
result=4*(count/1000000)
result

np.float64(3.141864)

In [196]:
np.random.seed(42)
points = np.random.rand(1_000_000, 2)
inside = np.sum(np.sum(points**2, axis=1) <= 1)
pi_estimate = 4 * inside / 1_000_000
pi_estimate

array([0.59515562, 0.36471714, 0.00537562, ..., 0.68311082, 0.33865907,
       0.69161641], shape=(1000000,))

##### 1️⃣1️⃣ Column-wise random noise

* Create a `(5,5)` zero matrix
* Add:

  * column-wise Gaussian noise
  * mean = `[0, 5, 10, 15, 20]`
  * std = `1`


In [215]:
np.random.seed(42)
mat=np.random.randn(5,5)
means=np.array([0,5,10,15,20])
mat+means

array([[ 0.49671415,  4.8617357 , 10.64768854, 16.52302986, 19.76584663],
       [-0.23413696,  6.57921282, 10.76743473, 14.53052561, 20.54256004],
       [-0.46341769,  4.53427025, 10.24196227, 13.08671976, 18.27508217],
       [-0.56228753,  3.98716888, 10.31424733, 14.09197592, 18.5876963 ],
       [ 1.46564877,  4.7742237 , 10.0675282 , 13.57525181, 19.45561728]])

In [210]:
np.random.seed(42)
A = np.zeros((5,5))
means = np.array([0,5,10,15,20])
noise = np.random.normal(means, 1, (5,5))
result = A + noise
result

array([[ 0.49671415,  4.8617357 , 10.64768854, 16.52302986, 19.76584663],
       [-0.23413696,  6.57921282, 10.76743473, 14.53052561, 20.54256004],
       [-0.46341769,  4.53427025, 10.24196227, 13.08671976, 18.27508217],
       [-0.56228753,  3.98716888, 10.31424733, 14.09197592, 18.5876963 ],
       [ 1.46564877,  4.7742237 , 10.0675282 , 13.57525181, 19.45561728]])

##### 1️⃣2️⃣ Random walk

Simulate a **1D random walk** of length `1000`:

* Steps = `+1` or `-1`
* Compute:

  * final position
  * max distance from origin


In [226]:
np.random.seed(42)
steps=np.random.choice([-1,1],1000)
walk=np.cumsum(steps)
final_position=walk[-1]
max_distance=np.max(np.abs(walk))
max_distance

np.int64(41)

##### 1️⃣3️⃣ Sampling without replacement

* Randomly select **10 unique numbers** from range `1–100`
* Sort them
* Compute pairwise differences

In [245]:
np.random.seed(42)
nums=np.random.choice(np.arange(1,101),10,replace=False)
nums.sort()
diffs=np.diff(nums)
diffs


array([10, 12, 17,  5,  1,  8, 17, 10,  3])

#####  1️⃣4️⃣ Random weighted matrix

* Generate a `(4,4)` matrix from `uniform(0,1)`
* Multiply each row by random weights from `normal(mean=10, std=2)`
* Normalize final matrix between `0` and `1`


In [247]:
np.random.seed(42)
A=np.random.rand(4,4)
weights=np.random.normal(10,2,4).reshape(4,1)
weighted= A*weights
normalized = (weighted - weighted.min())/(weighted.max()-weighted.min())
normalized

array([[0.38564585, 1.        , 0.76678621, 0.62461533],
       [0.08424607, 0.08423093, 0.02275581, 0.5301312 ],
       [0.38673935, 0.45799263, 0.        , 0.63242407],
       [0.73771015, 0.17795967, 0.15041539, 0.1518412 ]])

In [138]:
# (arr - min) / (range). # Normalization Formula