# **Shape**

### **`arr.shape` : To find Shape**
### **`arr.ndim` : To find Dimension**


In [7]:
import numpy as np


arr=np.array([[1,2,3,4],[1,2,3,4]])
arr.shape

arr=np.array([1,2,3,4],ndmin=4)
arr.ndim
arr.shape

(1, 1, 1, 4)

# **Reshape**
#### **`arr.reshape(shape(rows, cols),order='A/C/F')`**
### Rules
* Total elements must remain the same `rows × columns = arr.size`
* Only one dimension can be `-1` (NumPy auto-calculates it)
* Does not change data, only shape
* Returns a view if possible, otherwise a copy

`reshape()` changes how data is viewed, not the data itself.

#### Reshaping into 2D Array

In [25]:
arr1=np.array([1,2,3,4,5,6])
# arr1.reshape(3,3) #  3x3 = 9 != arr.size(6) ❌ size mismatch → error

arr1.reshape(3,2) # 3x2=6 =arr.size(6) Correct



array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
arr1.reshape(-1,1)
arr1.reshape(-1,3)
arr1.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Reshaping into 3D Array


In [39]:
arr2=np.array([1,2,3,4,5,6,7,8])
arr2.reshape(2,2,2)
arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2.reshape(3,2,2)
arr2.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Reshaping back to  1D Array


In [38]:
arr3=arr2.reshape(2,2,3)
arr3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])