# **Shape**

### **`arr.shape` : To find Shape**
### **`arr.ndim` : To find Dimension**


In [1]:
import numpy as np


arr=np.array([[1,2,3,4],[1,2,3,4]])
arr.shape

arr=np.array([1,2,3,4],ndmin=4)
arr.ndim
arr.shape

(1, 1, 1, 4)

# **Reshape**
#### **`arr.reshape(shape(rows, cols),order='A/C/F')`**
### Rules
* Total elements must remain the same `rows × columns = arr.size`
* Only one dimension can be `-1` (NumPy auto-calculates it)
* Does not change data, only shape
* Returns a view if possible, otherwise a copy

`reshape()` changes how data is viewed, not the data itself.

#### Reshaping into 2D Array
##### **`reshape(row,col)`**


In [2]:
arr1=np.array([1,2,3,4,5,6])
# arr1.reshape(3,3) #  3x3 = 9 != arr.size(6) ❌ size mismatch → error

arr1.reshape(3,2) # 3x2=6 =arr.size(6) Correct



array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
arr1.reshape(-1,1)
arr1.reshape(-1,3)
arr1.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Reshaping into 3D Array
##### **`reshape(block,row,col)`**


In [4]:
arr2=np.array([1,2,3,4,5,6,7,8])
arr2.reshape(2,2,2)
arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2.reshape(3,2,2)
arr2.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Reshaping back to  1D Array


In [5]:
arr3=arr2.reshape(2,2,3)
arr3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

---
# **Practice Problems**


##### 🔹 1️⃣ Reshape with inference

Create an array of numbers `1–72` and reshape it into **3D** such that:

* First dimension = 3
* Last dimension = 4
* Middle dimension is inferred automatically

👉 Print the final shape.


In [87]:
arr=np.arange(1,73)
arr.reshape(3,-1,4).shape

(3, 6, 4)

#### 🔹 2️⃣ Column-major reshaping

Given:

```python
a = np.arange(1,13)
```

Reshape it into a `(3,4)` matrix **column-wise** (Fortran order).


In [88]:
a=np.arange(1,13)
a.reshape(3,4,order='F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])


##### 🔹 3️⃣ Reverse reshape

Create a `(4,6)` matrix such that:

* Row-wise reading gives numbers `0–23`
* Column-wise reading gives numbers `0–23`

*(Hint: same data, different reshape logic)*


In [93]:
row=np.arange(0,24).reshape(4,6)
col=np.arange(0,24).reshape(4,6,order='F')
col

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

##### 🔹 4️⃣ Collapse selective axes

Create a `(2,3,4)` array.
Collapse only the **last two dimensions** into one, keeping the first intact.

Final shape must be `(2,12)`.


In [96]:
arr=np.arange(0,24).reshape(2,3,4)
arr.reshape(2,-1).shape

(2, 12)

##### 🔹 5️⃣ Expand dimensions correctly

Start with:

```python
a = np.array([1,2,3,4])
```

Convert it into a shape `(1,4,1)` **without reshaping manually by numbers**.


In [97]:
a=np.array([1,2,3,4])
a[np.newaxis :,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

##### 🔹 6️⃣ Alternating flatten

Given a `(4,4)` matrix:

* Flatten **row-wise**
* Reshape into `(2,8)`
* Then reshape into `(8,2)` **column-wise**


In [98]:
arr=np.arange(0,16).reshape(4,4)
arr.reshape(-1)
arr.reshape(2,8)
arr.reshape(8,2,order='F')

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

##### 🔹 7️⃣ Impossible reshape (logic check)

Explain **why** this fails and fix it:

```python
a = np.arange(20)
a.reshape(3,7)
```

*(No code execution needed — shape logic only)*


In [99]:
a=np.arange(20)
# a.reshape(3,7) # 3x7 = 21 != 20
a.reshape(4,5)
# OR
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])


##### 🔹 8️⃣ Diagonal extraction reshape

Create a `(5,5)` matrix.
Extract its diagonal and reshape it into a `(5,1)` column vector.


In [101]:
a=np.arange(25).reshape(5,5)
diagonal=a.diagonal()
diagonal.reshape(-1,1)


array([[ 0],
       [ 6],
       [12],
       [18],
       [24]])

##### 🔹 9️⃣ Axis swap without transpose

Create a `(3,4,5)` array.
Rearrange axes to get shape `(5,3,4)` **without using `.transpose()`**.


In [103]:
a=np.arange(60).reshape(3,4,5)
b=np.moveaxis(a,2,0)
b.shape

(5, 3, 4)

##### 🔹 🔟 Dynamic reshape

Create a `(6,8)` array and reshape it into **any 3D shape** such that:

* One dimension = 4
* Total elements remain unchanged
* One dimension is inferred

Print the final shape.

In [107]:
a=np.arange(48).reshape(6,8)
a.reshape(4,4,-1).shape
a.reshape(4,-1,2).shape

(4, 6, 2)

##### 🔹 1️⃣1️⃣ Memory view vs copy

Create a `(4,4)` array.
Reshape it into `(2,8)` and modify one element.

Check whether the original array changes **without copying**.

*(This tests deep understanding of views vs copies)*


In [85]:
a=np.arange(16).reshape(4,4)
a1=a.reshape(2,8)
a1[0,0]=11
a1

array([[11,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [86]:
a

array([[11,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### **`a1` is just a new pointer to `a` even if the shape is changed but still array is same**

#### **✅ Output shows original changed → `reshape()` returns a view, not a copy (when possible).**