# **Slicing**

> an operation in computer programming that extracts a **subset of elements** from an array or sequence, packaging them as another array or a view of the original data.

## **1D Array Slicing**
#### **`arr[start : stop : step (Optional)]`**

* Sliced Array is always `start-stop-1` 
* It Doesn't inlclude end value

```python
arr[1:4]
arr[-3:-1]
arr[1:-1]
```

In [14]:
import numpy as np

arr=np.array([1,2,3,4,5])

arr[1:4]
arr[1:-1]
arr[-3:-1]

array([3, 4])

## **2D Array Slicing**
#### **`arr[row-start : row-stop : row-step, col-start : col-stop : col-step]`**

```python
arr[0:2,0:2]
arr[-3:-1,-3:-1]
arr[0:2,-3:-1]
```

In [21]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

arr[0:2,0:2]
arr[-3:-1,-3:-1]
arr[0:2,-3:-1]


array([[1, 2],
       [4, 5]])

## **3D Array Slicing**
#### **`arr[block-start : block-stop : block-step, row-start : row-stop : row-step, col-start : col-stop : col-step]`**

```python
arr[1:2,0:2,0:2]
arr[-2:-1,-3:-1,-3:-1]
arr[1:2,0:-1,-3:-1]
```

In [24]:
arr=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],

               [[10,11,12],
                [13,14,15],
                [16,17,18]],

                [[19,20,21],
                 [22,23,24],
                 [25,26,27]]])

arr[1:2,0:2,0:2]
arr[-2:-1,-3:-1,-3:-1]
arr[1:2,0:-1,-3:-1]

array([[[10, 11],
        [13, 14]]])