# **Slicing**

> an operation in computer programming that extracts a **subset of elements** from an array or sequence, packaging them as another array or a view of the original data.

## **1D Array Slicing**
#### **`arr[start : stop : step (Optional)]`**

* Sliced Array is always `start-stop-1` 
* It Doesn't inlclude end value

```python
arr[1:4]
arr[-3:-1]
arr[1:-1]
```

In [2]:
import numpy as np

arr=np.array([1,2,3,4,5])

arr[1:4]
arr[1:-1]
arr[-3:-1]

array([3, 4])

## **2D Array Slicing**
#### **`arr[row-start : row-stop : row-step, col-start : col-stop : col-step]`**

```python
arr[0:2,0:2]
arr[-3:-1,-3:-1]
arr[0:2,-3:-1]
```

In [3]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

arr[0:2,0:2]
arr[-3:-1,-3:-1]
arr[0:2,-3:-1]


array([[1, 2],
       [4, 5]])

## **3D Array Slicing**
#### **`arr[block-start : block-stop : block-step, row-start : row-stop : row-step, col-start : col-stop : col-step]`**

```python
arr[1:2,0:2,0:2]
arr[-2:-1,-3:-1,-3:-1]
arr[1:2,0:-1,-3:-1]
```

In [4]:
arr=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],

               [[10,11,12],
                [13,14,15],
                [16,17,18]],

                [[19,20,21],
                 [22,23,24],
                 [25,26,27]]])

arr[1:2,0:2,0:2]
arr[-2:-1,-3:-1,-3:-1]
arr[1:2,0:-1,-3:-1]

array([[[10, 11],
        [13, 14]]])

---
# **Practice Problems**


##### 1️⃣ Reverse-alternate rows

Create a `6×6` array `0–35`.
Extract **only even rows**, but **reverse every selected row**.

📌 Output shape: `(3, 6)`


In [5]:
arr=np.arange(36).reshape(6,6)
arr[::2,::-1].shape

(3, 6)

##### 2️⃣ Border extraction (no loops)

From a `5×5` array, extract **only the border elements** as a 1D array in clockwise order.

📌 Top → Right → Bottom → Left

In [65]:
arr=np.arange(25).reshape(5,5)
top=arr[0]
right=arr[1:-1,-1]
bottom=arr[-1,::-1]
left=arr[-2:0:-1,0]
result=np.concatenate([top,right,bottom,left])
result

array([ 0,  1,  2,  3,  4,  9, 14, 19, 24, 23, 22, 21, 20, 15, 10,  5])


##### 3️⃣ Checkerboard via slicing

Using slicing **only**, create a `8×8` checkerboard of `0` and `1`.

❌ No loops
❌ No broadcasting tricks


In [7]:
checkerboard=np.zeros((8,8)).astype(int)
checkerboard[::2,1::2]=1
checkerboard[1::2,::2]=1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


##### 4️⃣ Diagonal band

From a `7×7` array, extract the **main diagonal plus 1 upper & 1 lower diagonal** as a matrix.

📌 Shape `(7,3)`


In [60]:
arr=np.arange(49).reshape(7,7)

lower= np.r_[np.nan,arr[1:,:-1].diagonal()]
main=arr.diagonal()
upper=np.r_[arr[:-1, 1:].diagonal(), np.nan]

band = np.column_stack((lower, main, upper))
band

array([[nan,  0.,  1.],
       [ 7.,  8.,  9.],
       [15., 16., 17.],
       [23., 24., 25.],
       [31., 32., 33.],
       [39., 40., 41.],
       [47., 48., nan]])


##### 5️⃣ Strided column extraction

From a `10×10` array, extract **every 3rd column**, but only rows `2–8`.

📌 Shape `(7,4)`


In [9]:
arr=np.arange(100).reshape(10,-1)
arr[2:9,::3].shape

(7, 4)

##### 6️⃣ Cross pattern

From a `9×9` array, extract a **plus (+) shape**:

* Middle row
* Middle column

Return as **two separate arrays**.


In [70]:
arr=np.arange(81).reshape(9,-1)
mid=arr.shape[0]//2
midRow=arr[mid,:]
midCol=arr[:,mid]
midRow,midCol

(array([36, 37, 38, 39, 40, 41, 42, 43, 44]),
 array([ 4, 13, 22, 31, 40, 49, 58, 67, 76]))


##### 7️⃣ Reverse inner matrix

From a `6×6` array:

* Keep the border unchanged
* Reverse the **inner 4×4** both row-wise and column-wise

📌 Final shape `(6,6)`


In [11]:
arr=np.arange(36).reshape(6,-1)
rev_subArray=arr[-2:0:-1,-2:0:-1]
arr[1:-1,1:-1]=rev_subArray
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6, 28, 27, 26, 25, 11],
       [12, 22, 21, 20, 19, 17],
       [18, 16, 15, 14, 13, 23],
       [24, 10,  9,  8,  7, 29],
       [30, 31, 32, 33, 34, 35]])

##### 8️⃣ Pyramid slice

From a `10×10` array, extract rows such that:

* Row 0 → columns `0:10`
* Row 1 → columns `1:9`
* Row 2 → columns `2:8`
* …

📌 No loops
📌 Output is ragged (list of arrays allowed)


In [47]:
arr=np.arange(100).reshape(10,-1)

pyramid=[arr[i, i:10-1]for i in range(5)]
pyramid

[array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([11, 12, 13, 14, 15, 16, 17, 18]),
 array([22, 23, 24, 25, 26, 27, 28]),
 array([33, 34, 35, 36, 37, 38]),
 array([44, 45, 46, 47, 48])]

##### 9️⃣ Boolean slicing challenge

From a `6×6` array:

* Extract values **above main diagonal**
* Extract values **below anti-diagonal**

Return both as 1D arrays.


In [77]:
arr=np.arange(36).reshape(6,6)
i,j=np.indices(arr.shape)

above_main=arr[i<j]
dia=arr.diagonal()
below_anti=arr[i+j>5]
above_main,dia,below_anti

(array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 15, 16, 17, 22, 23, 29]),
 array([ 0,  7, 14, 21, 28, 35]),
 array([11, 16, 17, 21, 22, 23, 26, 27, 28, 29, 31, 32, 33, 34, 35]))

In [74]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [72]:
a = np.arange(36).reshape(6, 6)
i, j = np.indices(a.shape)

above_main = a[i < j]
below_anti = a[i + j > 5]

above_main, below_anti


(array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 15, 16, 17, 22, 23, 29]),
 array([11, 16, 17, 21, 22, 23, 26, 27, 28, 29, 31, 32, 33, 34, 35]))

##### 🔟 Slice vs view trap

Given:

```python
a = np.arange(36).reshape(6,6)
b = a[1:5, 1:5]
b[:] = -1
```

🔹 What happens to `a`?
🔹 Why?

(Conceptual — no code)


`b` is a VIEW of `a`
Changing `b` modifies `a`
Because slicing usually returns a view, not a copy


##### 1️⃣1️⃣ Double-step slicing

From a `12×12` array:

* Take every **2nd row**
* From that, take every **3rd column**
* Reverse final result vertically

📌 One chained slicing expression


In [41]:
arr=np.arange(144).reshape(12,-1)
arr[::2,::3][::-1]


array([[120, 123, 126, 129],
       [ 96,  99, 102, 105],
       [ 72,  75,  78,  81],
       [ 48,  51,  54,  57],
       [ 24,  27,  30,  33],
       [  0,   3,   6,   9]])

##### 1️⃣2️⃣ Diagonal zig-zag slice (HARD)

From a `10×10` array, extract elements:

```
(0,0), (1,1), (2,2), ...
but reverse every alternate block of 3
```

📌 Output: 1D array

In [63]:
arr=np.arange(100).reshape(10,-1)
diag=arr.diagonal().copy()

usable = diag[:len(diag) - len(diag) % 3]
blocks=usable.reshape(-1,3)
blocks[1::2 ]=blocks[1::2, ::-1]

zigzag=blocks.ravel()
zigzag


array([ 0, 11, 22, 55, 44, 33, 66, 77, 88])